config/routes.rb
Rails.application.routes.draw do
  resources :components
  resources :bike_orders do
    collection do
      post 'check_bike_order'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "bike_orders#index"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest



end

app/models/bike_order.rb
class BikeOrder < ApplicationRecord
  validates_with BikeOrderValidator

  attr_accessor :warnings
  
  belongs_to :user
  has_many :bike_order_items, dependent: :delete_all
  
  accepts_nested_attributes_for :bike_order_items, allow_destroy: true

  def calculate_bike_order_prices!
    bike_order_items.each{|boi| boi.calculate_price }
  end
end

app/controllers/bike_orders_controller.rb
class BikeOrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bike_order, only: %i[ show edit update destroy ]

  # GET /bike_orders or /bike_orders.json
  def index
    @bike_orders = BikeOrder.all.where(user_id: current_user.id)
  end

  # GET /bike_orders/1 or /bike_orders/1.json
  def show
  end

  # GET /bike_orders/new
  def new
    @bike_order = BikeOrder.new
    build_bike_order_items  
  end

  # GET /bike_orders/1/edit
  def edit
    build_bike_order_items
  end

  # POST /bike_orders or /bike_orders.json
  def create
    @bike_order = BikeOrder.new(bike_order_params)
    @bike_order.user = current_user
    build_bike_order_items
    @bike_order.calculate_bike_order_prices!

    respond_to do |format|
      if @bike_order.save
        format.html { redirect_to @bike_order, notice: "Bike order was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /bike_orders/1 or /bike_orders/1.json
  def update
    build_bike_order_items
    @bike_order.calculate_bike_order_prices!
    respond_to do |format|
      if @bike_order.update(bike_order_params)
        format.html { redirect_to @bike_order, notice: "Bike order was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /bike_orders/1 or /bike_orders/1.json
  def destroy
    @bike_order.destroy!

    respond_to do |format|
      format.html { redirect_to bike_orders_path, status: :see_other, notice: "Bike order was successfully destroyed." }
    end
  end

  # POST /bike_orders/check_bike_order.js
  def check_bike_order
    @bike_order = BikeOrder.new(bike_order_params)
    @bike_order.calculate_bike_order_prices!
    
    respond_to do |format|
      format.js { render layout: false }
    end
 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike_order
      @bike_order = BikeOrder.includes(bike_order_items: :component).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bike_order_params
      params.require(:bike_order).permit(:id, :observations, bike_order_items_attributes: [:id, :component_id])
    end

    def build_bike_order_items
      if @bike_order.bike_order_items.empty?
        Component.component_types.each {|c_type| @bike_order.bike_order_items.build(ctype: c_type) }
      else
        present_ctypes = []
        @bike_order.bike_order_items.each{ |m| m.ctype= m.component&.c_type; (present_ctypes << m.ctype if m.ctype.present?) }
        absent_ctypes = Component.component_types - present_ctypes
        @bike_order.bike_order_items.select{|m| m.ctype.nil?}.zip(absent_ctypes).each do |boi, ac|
          boi.ctype=ac
        end
      end
    end
end

app/helpers/bike_orders_helper.rb
module BikeOrdersHelper

        # Given a set of selected components, filter those that cannot be selected in the next step
        def components_not_available(components_selected)
            return components_not_available_full_form(components_selected) if components_selected.length == Component.component_types.length
            if components_selected.blank?
                ccs = ComponentConstraint.includes(:components).joins(:components).distinct
            else
                ccs = ComponentConstraint.joins(:components).where(:components => { id: [ components_selected.map(&:id) ]}).distinct
            end
            
            result = ccs.inject([]) do |memo, cc|
                diff = cc.components - components_selected
                (memo = memo+diff) if diff.length == 1
                memo
            end.uniq
            result
        end
        
        def components_not_available_full_form(components_selected)
            result = components_selected.inject(Set[]) do |memo, c|
                c_aux = components_selected-[c]
                memo = memo+components_not_available(c_aux)
                memo
            end
            result
        end

end

app/views/bike_orders/_bike_order.html.erb
<div id="<%= dom_id bike_order %>">
</div>

app/views/bike_orders/_form.html.erb
<%= form_with(model: bike_order, id: 'bike-order-form', local: true, data: { turbo: false }) do |form| %>
  <%= form.hidden_field :id %>
  <div class="form-group mb-2"> 
    <%= form.fields_for :bike_order_items do |ff| %>
      <%= ff.label ff.object.ctype, class: "form-label" %>
      <%= ff.select :component_id, Component.components_by_component_type(ff.object.ctype).map { |i| [i.name, i.id] }, { include_blank: "Select #{ff.object.ctype}" }, { class: "form-select select-component" } %>
    <% end %>
  </div>

    <div class="form-group my-5">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>

<% if bike_order.errors.any? %>
    <div id="error_explanation">
      <h2>Following error were found (<%= pluralize(bike_order.errors.count, "error") %>):</h2>
      <ul>
        <% bike_order.errors.each do |error| %>
          <li><%= error.attribute == :custom ? error.type : error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/bike_orders/_order_details.html.erb
<% bike_order = @bike_order %>
<div id='order-details'>
  <div class='container order-items-components'>
  <div class="row"><div class="col-md-8 col-lg-9"><h2 class="text-center">Order Details</h2> </div></div>
    <% bike_order.bike_order_items.each do |boi| %>
      <% next unless boi.component %>
      <div class="row">
        <div class="col-md-8 col-lg-9">
          <p class='my-1'><%= boi.component.c_type %>: <%= boi.component.name %></p>
        </div>
        <div class="col-md-4 col-lg-3">
          <p class='my-0'>
            <% if boi.warnings %>
              <del><%= boi.component.price %>€</del>
            <% end %>
          <%= boi.price %>€
          </p>
        </div>
      </div>
      <% if boi.warnings %>
        <div class="row">
          <div class="col-md-8 alert alert-danger small py-0 mx-4">
            &#8627;  <%= boi.warnings %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <hr class="bg-danger border-2 border-top border-primary" />
  <div class='container'>
    <div class="row fw-bold">
      <div class="col-md-8 col-lg-9">
        <p>Total</p>
      </div>
      <div class="col-md-4 col-lg-3">
        <%= bike_order.bike_order_items.map{|boi| boi.price.to_i}.sum %>€
      </div>
    </div>
  </div>

  <div class='container order-item-warnings'>
    <%= bike_order.warnings %>
  </div>
</div>

                

app/views/bike_orders/check_bike_order.js.erb
$("#order-details").replaceWith("<%= j(render partial: "order_details") %>");
$(".select-component option").prop('disabled', false);
<% components_not_available(@bike_order.bike_order_items.map(&:component).uniq.compact).each do |c_unavailable| %>
    $('.select-component option[value="<%= c_unavailable.id %>"]').prop('disabled', true);
<% end %>

app/views/bike_orders/edit.html.erb
<div class="container-fluid">
  <div class="row bt-6">
    <div class="col-lg-6">
      <h1>Editing Bike Order</h1>

      <%= render 'form', bike_order: @bike_order %>

    </div>
    <div class="col-lg-6 bg-secondary">
      <%= render 'order_details', bike_order: @bike_order %>
    </div>
  </div>
  <%= link_to 'Back', bike_orders_path, class: "btn btn-light min-width-btn" %>
</div>

<script>
  document.addEventListener('turbo:load', function() {
  <% components_not_available(@bike_order.bike_order_items.map(&:component).uniq.compact).each do |c_unavailable| %>
      $('.select-component option[value="<%= c_unavailable.id %>"]').prop('disabled', true);
  <% end %>
});
</script>

app/views/bike_orders/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>
  <h1>Bike Orders</h1>
  <table class="table">
    <thead>
      <tr>
          <th colspan="3"></th>
      </tr>
    </thead>
<tbody>
      <% @bike_orders.each do |bike_order| %>
        <tr>
          <td><%= bike_order.created_at %></td>
            <td><%= link_to 'Show', bike_order %></td>
          <td><%= link_to 'Edit', edit_bike_order_path(bike_order) %></td>
          <td><%= link_to 'Destroy', bike_order, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br />
  <%= link_to 'New Bike Order', new_bike_order_path, class: "btn btn-success min-width-btn" %>
</div>

app/views/bike_orders/new.html.erb
<div class="container-fluid">
  <div class="row bt-6">
    <div class="col-lg-6">
      <h1>New Bike Order</h1>

      <%= render 'form', bike_order: @bike_order %>

    </div>
    <div class="col-lg-6 bg-secondary">
      <%= render 'order_details', bike_order: @bike_order %>
    </div>
  </div>
  <%= link_to 'Back', bike_orders_path, class: "btn btn-light min-width-btn" %>
</div>

  <script>
      document.addEventListener('turbo:load', function() {
      <% components_not_available(@bike_order.bike_order_items.map(&:component).uniq.compact).each do |c_unavailable| %>
          $('.select-component option[value="<%= c_unavailable.id %>"]').prop('disabled', true);
      <% end %>
    });
  </script>

app/views/bike_orders/show.html.erb
<div class="container-fluid">
  <%= render 'order_details', bike_order: @bike_order %>
<p>Order creation: <%= @bike_order.created_at.to_formatted_s(:long) %></p>
<p>Order last update: <%= @bike_order.updated_at.to_formatted_s(:long) %></p>
<%= link_to 'Edit', edit_bike_order_path(@bike_order), class: "btn btn-primary min-width-btn" %>
  <%= link_to 'Back', bike_orders_path, class: "btn btn-light min-width-btn" %>
</div>